### ISSUE TITLE
Add support for Browserify

### ISSUE THREAD

**Issue by petebrowne** [megawac/MutationObserver.js#11]
This line does not work in browserify, because `this` is not the window:

``` javascript
this.MutationObserver = this.MutationObserver || this.WebKitMutationObserver || (function(){/* ... */})(void 0);
```

Changing it to this works:

``` javascript
this.MutationObserver = window.MutationObserver || window.WebKitMutationObserver || (function(){/* ... */})(void 0);
```

**Comment by stephanebachelier** [comment]
@megawac This is the same for require.js

**Comment by megawac** [comment]
@stephanebachelier I've only used AMD via dojo, is the wrapper (https://github.com/stephanebachelier/MutationObserver.js/commit/0d93d9d6e2eb2a57058206aa4d1dc02ad2a2a9b9) really necessary for `require.js` support?

**Comment by stephanebachelier** [comment]
@megawac I forgot to update my comment. It was too much pain to modify the tests for ... no gain.

You're absolutely right: no need for AMD wrapper. The MutationObserver must be attached to window.

**Comment by megawac** [comment]
Sweet, should be good I hope in that case. Can you confirm whether something like this would be possible with `require`?

```js
require.config({
    shim: {
        MutationObserver: {
            exports: 'MutationObserver'
        }, 
        c3: {
           deps: ["MutationObserver"]
        }
    },
    paths: {
        MutationObserver: window.MutationObserver ? null : "/depends/MutationObserver/dist/mutationobserver.min.js",
       c3: "/path/to/c3"
    }
});
```

[Reference](https://github.com/masayuki0812/c3/issues/920#issuecomment-72092058)
