### ISSUE TITLE
IE8 examples are not working

### ISSUE THREAD

**Issue by isatimur** [megawac/MutationObserver.js#17]
Hi,
I was looking for pollyfils like yours in IE8 to use it as DOMNodeInserted event, but when I started checking example in ie8 under windows 7 , I have discovered that those samples don't work at all, for instance image is loaded with errors.

**Comment by megawac** [comment]
Yeah, github updated some urls http://jsbin.com/suqewogone

**Comment by isatimur** [comment]
Cool! thx a lot! Will try to use it!
