### ISSUE TITLE
Sauce Labs browser matrix shows incorrect results

### ISSUE THREAD

**Issue by mnaoumov** [megawac/MutationObserver.js#24]
I've raised a corresponding question for Sauce Labs team
https://support.saucelabs.com/customer/en/portal/questions/13019208-browser-matrix-svg-doesn-t-represent-the-recent-results?new=13019208

**Comment by megawac** [comment]
Yeah, I submitted a ticket with them about a year ago and it never got fixed
http://support.saucelabs.com/requests/14963

**Comment by mnaoumov** [comment]
@megawac your link returns 404

**Comment by mnaoumov** [comment]
@megawac Sauce Labs said they fixed the issue https://support.saucelabs.com/customer/en/portal/questions/13019208-browser-matrix-svg-doesn-t-represent-the-recent-results?new=13019208

However I don't see any test running here anymore https://saucelabs.com/u/mutationobserver

**Comment by megawac** [comment]
Sauce has fixed the issue (finally)
