### ISSUE TITLE
Can't add event listener to addedNodes from mutations

### ISSUE THREAD

**Issue by Jeloo** [megawac/MutationObserver.js#25]
Hi. I'm trying to attach handlers to addedNodes events. I test it in ie9, trying to get it working with 'a' elements. It's working on original MutationObserver (tested on latest chrome), but not on polyfill.
Here is my example code.

http://plnkr.co/edit/mJ2Hlw0PzI4ZSIdus6rq?p=preview

Thanks.

**Comment by megawac** [comment]
Is it throwing an error or silently failing in ie?

**Comment by Jeloo** [comment]
Hi. Thanks for your reply.
Sorry, it was my bad. It's working properly so i should close the issue.
