### ISSUE TITLE
characterData mutation not detected

### ISSUE THREAD

**Issue by laurentgoudet** [megawac/MutationObserver.js#27]
Ref systemjs/systemjs/issues/1157. This shim silently breaks SystemJS as the `characterData` mutation used in its Promise polyfill is not detected:

```
		var scheduled;
		var node = document.createTextNode('');
		var o = new MutationObserverShim(run);
		o.observe(node, { characterData: true });

                // run is never called
		function run() {
			var f = scheduled;
			scheduled = void 0;
			f();
		}

		var i = 0;
		return function (f) {
			scheduled = f;
			node.data = (i ^= 1);
		};
```

The documentation seems to suggest that `characterData` mutations are handled, but looking at the code path I'm not sure how. Is the code above meant to work with the shim? Thanks!

**Comment by megawac** [comment]
I haven't had a chance to look into this yet, but possibly related:
https://github.com/stefanpenner/es6-promise/pull/1
https://github.com/stefanpenner/es6-promise/pull/2

**Comment by MeirionHughes** [comment]
same; child lists are firing; but the text-node changes don't fire.

**Comment by MeirionHughes** [comment]
I don't know how this (text mutation) ever worked :D 

The code looks like it will only detect the text-change if there is a child-list conflict. Anyhow, simple fix to check early for text changes: 

https://github.com/aurelia/pal-nodejs/blob/master/src/polyfills/mutation-observer.ts#L248

thx for the polyfill @megawac

**Comment by megawac** [comment]
It should detect changes on the same node as well currently I think @MeirionHughes:

https://github.com/megawac/MutationObserver.js/blob/master/MutationObserver.js#L386

This case is entered without a child-list conflict. Child-list conflict char-data changes are handled separately.

I think the issue is it doesn't work when observing text-nodes directly

**Comment by megawac** [comment]
Oh actually, I get what you mean. Thanks @MeirionHughes want to submit a PR?
