### ISSUE TITLE
Error: Cannot assign to read only property 'MutationObserver' of object '[object Object]' in SalesForce

### ISSUE THREAD

**Issue by siawo** [megawac/MutationObserver.js#34]
Hi @megawac, I'm trying to use the Mutation Observer shim in my code which will run in SalesForce. The locker head console which checks the security of the script is logging errors from your polyfill. When I checked, the MutationObseerver which is read-only cannot be reassigned.
I have tested your minified file [here](https://developer.salesforce.com/docs/component-library/tools/locker-service-console).
The results were
![Screenshot 2020-03-10 at 2 23 00 PM (2)](https://user-images.githubusercontent.com/20562318/76298669-d6d90f80-62df-11ea-9ef5-982993a24b17.png)
With respect to this issue, I have created a [PR](https://github.com/megawac/MutationObserver.js/pull/33).

**Comment by siawo** [comment]
@megawac Can you please check this?

**Comment by siawo** [comment]
@megawac Any plans for the npm release?

**Comment by megawac** [comment]
Done, thank you for the reminder.
